### ISSUE TITLE
Enhancement - Display cash amount by denomination

### ISSUE THREAD

**Issue by narayanantce** [wengjjpaul/SCMFT05#1]
The system is required to provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer. This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

**Comment by Yarisha** [comment]
Impact Analysis has been completed.

**Comment by imkarthekeyan** [comment]
Technical evaluation is completed for enhancement and the change request form is updated.

**Comment by narayanantce** [comment]
Change request has been approved

**Comment by wengjjpaul** [comment]
Implemented enhancement fee5a00477edb8a5edb79a72c3f4ba7eeab623d4. Request for code review

**Comment by imkarthekeyan** [comment]
Code review is completed.

**Comment by Yarisha** [comment]
Testing and quality analysis have been completed.

**Comment by narayanantce** [comment]
Acceptance Sign off obtained. Ready for merge with master branch

**Comment by wengjjpaul** [comment]
Merged enhancement branch into master branch fee5a00477edb8a5edb79a72c3f4ba7eeab623d4

**Comment by narayanantce** [comment]
Approved for the release

**Comment by narayanantce** [comment]
Clearing assignee and closing the issue, since the code is tagged and released (1.0.9)
