### ISSUE TITLE
Defect - Reset values to NULL for "Show Total Cash Held" and "Press to Collect Cash"

### ISSUE THREAD

**Issue by Yarisha** [wengjjpaul/SCMFT05#2]

**Comment by rianagpal** [comment]
Performed Impact Analysis for the defect.

**Comment by imkarthekeyan** [comment]
Technical evaluation is completed and the change request form is updated.

**Comment by narayanantce** [comment]
Change request has been approved. Kindly proceed with coding.

**Comment by imkarthekeyan** [comment]
Code submitted - Please do technical review

**Comment by imkarthekeyan** [comment]
Technical Review - Completed & Assigning for QA.

**Comment by Yarisha** [comment]
Testing completed. Passed Quality Assurance.

**Comment by imkarthekeyan** [comment]
Technical evaluation is completed for enchancement and the change request form is updated.

**Comment by imkarthekeyan** [comment]
Technical evaluation is completed for enhancement and the change request form is updated.

**Comment by narayanantce** [comment]
Approved for the release

**Comment by Yarisha** [comment]
Clearing the assignee and closing the issue as the code has been tagged and released (1.0.9)
